swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: '127.0.0.1'
# basePath prefixes all resource paths 
basePath: /

schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - text/xml
  - application/pdf
  - text/html
  - text/plain
  - application/octet-stream
  - application/zip
  - application/msword
  - application/vnd.ms-excel
  - application/vnd.ms-powerpoint
  - image/gif
  - image/png
  - image/jpg
  - multipart/form-data
  - application/force-download
# format of the responses to the client (Accepts)
produces:
  - application/json
  - text/xml
  - application/pdf
  - text/html
  - application/octet-stream
  - application/zip
  - application/msword
  - application/vnd.ms-excel
  - application/vnd.ms-powerpoint
  - image/gif
  - image/png
  - image/jpg
  - application/force-download

paths:
  /:
    # binds a127 app logic to a route
    x-swagger-router-controller: user
    post:
      description: Returns token to user
      # used as the method name of the controller
      operationId: checkLogin
      parameters:
        - name: creds
          in: body
          description: The name of the person to whom to say hello
          schema: 
            type: string
            example: 
              username: username
              password: password
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /bookmarks:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      operationId: sendBook
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /documents:
    x-swagger-router-controller: strateskiDoc
    post:
      operationId: postDoc
      parameters:
        - name: model
          in: body
          schema: 
            type: object
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      operationId: getDoc
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /documents/{id}:
    x-swagger-router-controller: strateskiDoc
    delete:
    #brisemo tako sto stavljamo active u 0
      operationId: delDoc
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /osnovni_podaci:
    x-swagger-router-controller: osnovniPodaci
    post:
      operationId: saveOp
      parameters:
        - name: podaci
          in: body
          schema: 
            type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      operationId: getOP
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /uploadDoc:
    x-swagger-router-controller: strateskiDoc
    post:
      operationId: upload
      parameters:
        - name: document
          in: formData 
          type: file
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"         
  /downDoc/{file}:
    x-swagger-router-controller: strateskiDoc
    get:
      operationId: downloadDoc
      parameters:
        - name: file
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:

  HelloWorldResponse:
    type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
